I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 586, in script
    bam" with vpunch"
Exception: Sayer 'bam' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 586, in script
    bam" with vpunch"
  File "C:\Users\eduar\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 2560, in execute
    Say.execute(self)
  File "C:\Users\eduar\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\eduar\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'bam' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.3.24061702
 1.0
Tue Jul 16 22:21:01 2024
